### PR TITLE
docs: use QuickNode public RPC endpoints

### PR DESCRIPTION
**Pull request by jcstein**
## Summary

- add the canonical public QuickNode endpoints for Mainnet and Mocha
- update default HTTP, REST, WebSocket, gRPC, node, and trusted-hash examples
- retain community provider listings; bridge start examples now use an `<archival-consensus-endpoint>` placeholder with an archive-node warning, because public endpoints are pruned and cannot serve bridge sync from genesis
- align the Mocha hermes `rpc_addr` with the QuickNode `event_source` websocket so the relayer queries and subscribes to the same node
- remove the unused `mochaRpcUrl`/`mochaRestUrl`/`mainnetRpcUrl`/`mainnetRestUrl` constants (not referenced by any page)
- keep `--chain-id mocha-4` in the cli-reference tx example: the "mocha" alias only exists for celestia-node's `--p2p.network` flag, while celestia-appd signs transactions against the exact chain ID. Note: chain ID references will move to `mocha-5` with the network restart tracked in #2546.
- use QuickNode for both DA JSON-RPC and consensus gRPC in the Go client guide — the public endpoints serve celestia-node DA JSON-RPC on 443, and the full submit + retrieve flow was verified live on Mocha (blob at block 13821340). Both network pages now list the DA JSON-RPC interface.
- note the Go 1.25.x requirement in the Go guide (`bytedance/sonic` does not compile on Go 1.26 yet; `GOTOOLCHAIN=go1.25.1` workaround documented)

## Context

Tracks [DEVX-102](https://linear.app/celestia/issue/DEVX-102/switch-main-public-rpc-to-quicknode-enterprise-endpoint).

The endpoint aliases and Mainnet/Mocha split were confirmed in the [original Slack thread](https://celestia-team.slack.com/archives/C07TJQPUDJP/p1752701226522469?thread_ts=1750066245.925629&cid=C07TJQPUDJP).

## Validation

- live HTTP RPC, REST, authenticated-free CORS, WebSocket new-block subscriptions, and gRPC GetNodeInfo on both endpoints
- Mainnet archive query at height 1; Mocha confirmed pruned
- `npm run test:endpoints`
- `npm run lint` (passes with one unrelated existing warning)
- `npm run build`

### CODE REVIEW

**Comment by jcstein** [comment]
## Validation runbook results (2026-08-13)

All checks run against the public QuickNode endpoints referenced in this PR.

### Mainnet (`public-endpoint.celestia-mainnet.quiknode.pro`)

| Check | Result |
| --- | --- |
| HTTP RPC `/status` | ✅ synced, `catching_up: false`, `earliest_block_height: 1` (archive) |
| Archive query `/block?height=1` | ✅ serves block 1 |
| REST `/cosmos/base/tendermint/v1beta1/blocks/latest` | ✅ |
| gRPC over TLS (`GetNodeInfo`, port 9090) | ✅ celestia-app v9.0.4 |
| WebSocket `NewBlock` subscription | ✅ |
| DA JSON-RPC (`header.NetworkHead` on 443) | ✅ |
| Light node header sync (celestia-node v0.31.4, `--core.tls`) | ✅ |

### Mocha (`public-endpoint.celestia-mocha.quiknode.pro`)

| Check | Result |
| --- | --- |
| HTTP RPC `/status` | ✅ synced, pruned as expected (earliest ≈ 11805609) |
| REST latest block | ✅ |
| gRPC over TLS (`GetNodeInfo`, port 9090) | ✅ celestia-app v9.0.4 |
| WebSocket `NewBlock` subscription | ✅ live block received |
| DA JSON-RPC (`header.NetworkHead` on 443) | ✅ |
| Hermes RPC methods (`health`, `status`, `block_results`, `validators`, `abci_info`) | ✅ (validates the `rpc_addr` change) |
| Light node header sync (celestia-node v0.31.4-mocha, `--core.tls`) | ✅ reached network head; DAS `share: data not available` retries are p2p sampling, unrelated to the endpoint |

### Go client guide (end-to-end)

Ran the guide's exact `main.go`/`go.mod` with QuickNode for **both** DA JSON-RPC and consensus gRPC:

- ✅ account creation, balance query over Core gRPC
- ✅ blob submitted at block 13821340, retrieved, data verified

Note: build requires Go 1.25.x — `bytedance/sonic` v1.14.1 (transitive via celestia-node) does not compile on Go 1.26 (`undefined: GoMapIterator`). Workaround `GOTOOLCHAIN=go1.25.1` is documented in the guide; the real fix is a sonic bump in celestia-node.

File: app/operate/data-availability/bridge-node/page.mdx [hunk 1]
```diff
@@ -120,9 +120,13 @@ celestia bridge start --core.ip <URI> --core.port <port>
 Here is an example of starting the bridge node on Mocha:
 
 ```sh
-celestia bridge start --core.ip rpc-mocha.pops.one --core.port 9090 --p2p.network mocha
+celestia bridge start --core.ip <archive-consensus-endpoint> --core.port 9090 --p2p.network mocha
```
Comment (jcstein) [inline app/operate/data-availability/bridge-node/page.mdx]:
```suggestion
celestia bridge start --core.ip <archival-consensus-endpoint> --core.port 9090 --p2p.network mocha
```

File: app/operate/data-availability/bridge-node/page.mdx [hunk 2]
```diff
@@ -120,9 +120,13 @@ celestia bridge start --core.ip <URI> --core.port <port>
 Here is an example of starting the bridge node on Mocha:
 
 ```sh
-celestia bridge start --core.ip rpc-mocha.pops.one --core.port 9090 --p2p.network mocha
+celestia bridge start --core.ip <archival-consensus-endpoint> --core.port 9090 --p2p.network mocha
 ```
 
+<Callout type="warning">
+Bridge nodes sync headers from genesis and require an archive consensus node. Public RPC endpoints are typically pruned and will not work for initial sync — use your own archive consensus node or an archive endpoint from an infrastructure provider.
```
Comment (jcstein) [inline app/operate/data-availability/bridge-node/page.mdx]:
```suggestion
Bridge nodes sync headers from genesis and require an archival consensus node. Public RPC endpoints are typically pruned and will not work for initial sync. Use your own archival consensus node or an archival endpoint from an infrastructure provider.
```

File: app/operate/maintenance/troubleshooting/page.mdx [hunk 3]
```diff
@@ -105,7 +105,7 @@ celestia <node-type> init --node.store /home/user/celestia-<node-type>-location/
 Next, start your node:
 
 ```bash
-celestia bridge start --core.ip rpc-mocha.pops.one --p2p.network mocha \
+celestia bridge start --core.ip <archive-consensus-endpoint> --p2p.network mocha \
```
Comment (jcstein) [inline app/operate/maintenance/troubleshooting/page.mdx]:
```suggestion
celestia bridge start --core.ip <archival-consensus-endpoint> --p2p.network mocha \
```

**Review by jcstein — COMMENTED** [review]
reviewed with human eyes and lgtm. also tested all test cases above in comment

**Review by gbarros — APPROVED** [review]
